name: Build HARA_IOS
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          curl -LO
